version: '3.8'

services:
  article_postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: cool_service
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    

  article_rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # HTTP UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  article_jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "6831:6831/udp"   # UDP for tracing spans
      - "16686:16686"     # Jaeger UI
      - "14268:14268"     # Collector HTTP (used by OTEL)
      - "14250:14250"     # gRPC

  article_redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]


volumes:
  pgdata:
  redis_data:
