.PHONY:

### for running all commands we need bash command lien ###

## choco install make
# ==============================================================================
# Run Services
run_storage_service:
	cd service/storage/cmd/ && 	go run ./cmd/main.go

run_ai_summarization_service:
	cd service/ai-summarization/cmd/ && 	go run ./cmd/main.go


