// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc2
// source: description.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateDescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDescriptionRequest) Reset() {
	*x = GenerateDescriptionRequest{}
	mi := &file_description_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDescriptionRequest) ProtoMessage() {}

func (x *GenerateDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_description_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDescriptionRequest.ProtoReflect.Descriptor instead.
func (*GenerateDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_description_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDescriptionRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateDescriptionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GenerateDescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDescriptionResponse) Reset() {
	*x = GenerateDescriptionResponse{}
	mi := &file_description_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDescriptionResponse) ProtoMessage() {}

func (x *GenerateDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_description_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDescriptionResponse.ProtoReflect.Descriptor instead.
func (*GenerateDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_description_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDescriptionResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GenerateDescriptionResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_description_proto protoreflect.FileDescriptor

const file_description_proto_rawDesc = "" +
	"\n" +
	"\x11description.proto\x12\x05proto\"P\n" +
	"\x1aGenerateDescriptionRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"m\n" +
	"\x1bGenerateDescriptionResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords2r\n" +
	"\x12DescriptionService\x12\\\n" +
	"\x13GenerateDescription\x12!.proto.GenerateDescriptionRequest\x1a\".proto.GenerateDescriptionResponseB\x03Z\x01/b\x06proto3"

var (
	file_description_proto_rawDescOnce sync.Once
	file_description_proto_rawDescData []byte
)

func file_description_proto_rawDescGZIP() []byte {
	file_description_proto_rawDescOnce.Do(func() {
		file_description_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_description_proto_rawDesc), len(file_description_proto_rawDesc)))
	})
	return file_description_proto_rawDescData
}

var file_description_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_description_proto_goTypes = []any{
	(*GenerateDescriptionRequest)(nil),  // 0: proto.GenerateDescriptionRequest
	(*GenerateDescriptionResponse)(nil), // 1: proto.GenerateDescriptionResponse
}
var file_description_proto_depIdxs = []int32{
	0, // 0: proto.DescriptionService.GenerateDescription:input_type -> proto.GenerateDescriptionRequest
	1, // 1: proto.DescriptionService.GenerateDescription:output_type -> proto.GenerateDescriptionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_description_proto_init() }
func file_description_proto_init() {
	if File_description_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_description_proto_rawDesc), len(file_description_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_description_proto_goTypes,
		DependencyIndexes: file_description_proto_depIdxs,
		MessageInfos:      file_description_proto_msgTypes,
	}.Build()
	File_description_proto = out.File
	file_description_proto_goTypes = nil
	file_description_proto_depIdxs = nil
}
