// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.32.0--rc2
// source: description.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DescriptionServiceClient is the client API for DescriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DescriptionServiceClient interface {
	GenerateDescription(ctx context.Context, in *GenerateDescriptionRequest, opts ...grpc.CallOption) (*GenerateDescriptionResponse, error)
}

type descriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDescriptionServiceClient(cc grpc.ClientConnInterface) DescriptionServiceClient {
	return &descriptionServiceClient{cc}
}

func (c *descriptionServiceClient) GenerateDescription(ctx context.Context, in *GenerateDescriptionRequest, opts ...grpc.CallOption) (*GenerateDescriptionResponse, error) {
	out := new(GenerateDescriptionResponse)
	err := c.cc.Invoke(ctx, "/proto.DescriptionService/GenerateDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DescriptionServiceServer is the server API for DescriptionService service.
// All implementations must embed UnimplementedDescriptionServiceServer
// for forward compatibility
type DescriptionServiceServer interface {
	GenerateDescription(context.Context, *GenerateDescriptionRequest) (*GenerateDescriptionResponse, error)
	mustEmbedUnimplementedDescriptionServiceServer()
}

// UnimplementedDescriptionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDescriptionServiceServer struct {
}

func (UnimplementedDescriptionServiceServer) GenerateDescription(context.Context, *GenerateDescriptionRequest) (*GenerateDescriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDescription not implemented")
}
func (UnimplementedDescriptionServiceServer) mustEmbedUnimplementedDescriptionServiceServer() {}

// UnsafeDescriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DescriptionServiceServer will
// result in compilation errors.
type UnsafeDescriptionServiceServer interface {
	mustEmbedUnimplementedDescriptionServiceServer()
}

func RegisterDescriptionServiceServer(s grpc.ServiceRegistrar, srv DescriptionServiceServer) {
	s.RegisterService(&DescriptionService_ServiceDesc, srv)
}

func _DescriptionService_GenerateDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescriptionServiceServer).GenerateDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DescriptionService/GenerateDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescriptionServiceServer).GenerateDescription(ctx, req.(*GenerateDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DescriptionService_ServiceDesc is the grpc.ServiceDesc for DescriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DescriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DescriptionService",
	HandlerType: (*DescriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDescription",
			Handler:    _DescriptionService_GenerateDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "description.proto",
}
