// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: web_scraper.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_QUEUED    Status = 0
	Status_RUNNING   Status = 1
	Status_COMPLETED Status = 2
	Status_FAILED    Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "QUEUED",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
	}
	Status_value = map[string]int32{
		"QUEUED":    0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_web_scraper_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_web_scraper_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_web_scraper_proto_rawDescGZIP(), []int{0}
}

type ScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	mi := &file_web_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_web_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *ScrapeRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapeRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"` // queued | running | done | failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_web_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_web_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *ScrapeResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ScrapeResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_QUEUED
}

type GetResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultRequest) Reset() {
	*x = GetResultRequest{}
	mi := &file_web_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultRequest) ProtoMessage() {}

func (x *GetResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultRequest.ProtoReflect.Descriptor instead.
func (*GetResultRequest) Descriptor() ([]byte, []int) {
	return file_web_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *GetResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type PageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`         // cleaned text
	Markdown      string                 `protobuf:"bytes,4,opt,name=markdown,proto3" json:"markdown,omitempty"` // optional markdown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData) Reset() {
	*x = PageData{}
	mi := &file_web_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData) ProtoMessage() {}

func (x *PageData) ProtoReflect() protoreflect.Message {
	mi := &file_web_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData.ProtoReflect.Descriptor instead.
func (*PageData) Descriptor() ([]byte, []int) {
	return file_web_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *PageData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PageData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PageData) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

type GetResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"` // queued | running | done | failed
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Page          *PageData              `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"` // present when done
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultResponse) Reset() {
	*x = GetResultResponse{}
	mi := &file_web_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultResponse) ProtoMessage() {}

func (x *GetResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultResponse.ProtoReflect.Descriptor instead.
func (*GetResultResponse) Descriptor() ([]byte, []int) {
	return file_web_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *GetResultResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetResultResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_QUEUED
}

func (x *GetResultResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetResultResponse) GetPage() *PageData {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_web_scraper_proto protoreflect.FileDescriptor

const file_web_scraper_proto_rawDesc = "" +
	"\n" +
	"\x11web_scraper.proto\x12\x05proto\"@\n" +
	"\rScrapeRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"N\n" +
	"\x0eScrapeResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x06status\x18\x02 \x01(\x0e2\r.proto.StatusR\x06status\")\n" +
	"\x10GetResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"b\n" +
	"\bPageData\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1a\n" +
	"\bmarkdown\x18\x04 \x01(\tR\bmarkdown\"\x8c\x01\n" +
	"\x11GetResultResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x06status\x18\x02 \x01(\x0e2\r.proto.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12#\n" +
	"\x04page\x18\x04 \x01(\v2\x0f.proto.PageDataR\x04page*<\n" +
	"\x06Status\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\r\n" +
	"\tCOMPLETED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x032\x8b\x01\n" +
	"\x0eScraperService\x129\n" +
	"\n" +
	"ScrapePage\x12\x14.proto.ScrapeRequest\x1a\x15.proto.ScrapeResponse\x12>\n" +
	"\tGetResult\x12\x17.proto.GetResultRequest\x1a\x18.proto.GetResultResponseB\x03Z\x01.b\x06proto3"

var (
	file_web_scraper_proto_rawDescOnce sync.Once
	file_web_scraper_proto_rawDescData []byte
)

func file_web_scraper_proto_rawDescGZIP() []byte {
	file_web_scraper_proto_rawDescOnce.Do(func() {
		file_web_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_scraper_proto_rawDesc), len(file_web_scraper_proto_rawDesc)))
	})
	return file_web_scraper_proto_rawDescData
}

var file_web_scraper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_web_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_web_scraper_proto_goTypes = []any{
	(Status)(0),               // 0: proto.Status
	(*ScrapeRequest)(nil),     // 1: proto.ScrapeRequest
	(*ScrapeResponse)(nil),    // 2: proto.ScrapeResponse
	(*GetResultRequest)(nil),  // 3: proto.GetResultRequest
	(*PageData)(nil),          // 4: proto.PageData
	(*GetResultResponse)(nil), // 5: proto.GetResultResponse
}
var file_web_scraper_proto_depIdxs = []int32{
	0, // 0: proto.ScrapeResponse.status:type_name -> proto.Status
	0, // 1: proto.GetResultResponse.status:type_name -> proto.Status
	4, // 2: proto.GetResultResponse.page:type_name -> proto.PageData
	1, // 3: proto.ScraperService.ScrapePage:input_type -> proto.ScrapeRequest
	3, // 4: proto.ScraperService.GetResult:input_type -> proto.GetResultRequest
	2, // 5: proto.ScraperService.ScrapePage:output_type -> proto.ScrapeResponse
	5, // 6: proto.ScraperService.GetResult:output_type -> proto.GetResultResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_web_scraper_proto_init() }
func file_web_scraper_proto_init() {
	if File_web_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_scraper_proto_rawDesc), len(file_web_scraper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_scraper_proto_goTypes,
		DependencyIndexes: file_web_scraper_proto_depIdxs,
		EnumInfos:         file_web_scraper_proto_enumTypes,
		MessageInfos:      file_web_scraper_proto_msgTypes,
	}.Build()
	File_web_scraper_proto = out.File
	file_web_scraper_proto_goTypes = nil
	file_web_scraper_proto_depIdxs = nil
}
